version: '3'

services:
  overture:
    image: 'docker.io/firewalla/overture:latest'
    environment:
     - LOCAL_DNS=1.1.1.1
     - LOCAL_DNS_PORT=53
     - DOH_DNS1=dns1
     - DOH_DNS2=dns2
    ports:
      - "9953:9953/udp"
  trojan:
    network_mode: host
    image: 'docker.io/firewalla/trojan:latest'
    environment:
      - TROJAN_SERVER=server
      - TROJAN_PASSWORD=password
    ports:
      - "9954:9954/tcp"
  trojan_socks:
    image: 'docker.io/firewalla/trojan:latest'
    environment:
      - TROJAN_SERVER=server
      - TROJAN_PASSWORD=password
      - TROJAN_TYPE=client
      - TROJAN_LOCAL_PORT=9955
    ports:
      - "9955:9955/tcp"